// src/store/firebase.ts
// Frontend Firebase SDK connection.
// Connects all services to the Firebase emulators in non-production mode.
// Port values are read from PUBLIC_* environment variables generated by setup-ports.js.

import { initializeApp } from 'firebase/app'
import { getAuth, connectAuthEmulator } from 'firebase/auth'
import { getFirestore, connectFirestoreEmulator } from 'firebase/firestore'
import { getStorage, connectStorageEmulator } from 'firebase/storage'
import { getFunctions, connectFunctionsEmulator } from 'firebase/functions'

const firebaseConfig = {
  // Fill in your project's config values.
  apiKey: import.meta.env.PUBLIC_FIREBASE_API_KEY,
  authDomain: import.meta.env.PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.PUBLIC_FIREBASE_APP_ID,
}

const app = initializeApp(firebaseConfig)
const auth = getAuth(app)
const firestore = getFirestore(app)
const storage = getStorage(app)
const functions = getFunctions(app)

if (import.meta.env.MODE !== 'production') {
  // Auth
  const authHost = import.meta.env.PUBLIC_FIREBASE_AUTH_EMULATOR_HOST
  if (!authHost) throw new Error('PUBLIC_FIREBASE_AUTH_EMULATOR_HOST is required')
  connectAuthEmulator(auth, `http://${authHost}`, { disableWarnings: true })

  // Firestore
  const firestoreHost = import.meta.env.PUBLIC_FIRESTORE_EMULATOR_HOST
  if (!firestoreHost) throw new Error('PUBLIC_FIRESTORE_EMULATOR_HOST is required')
  const [firestoreHostname, firestorePort] = firestoreHost.split(':')
  connectFirestoreEmulator(firestore, firestoreHostname, Number(firestorePort))

  // Storage
  const storageHost = import.meta.env.PUBLIC_FIREBASE_STORAGE_EMULATOR_HOST
  if (!storageHost) throw new Error('PUBLIC_FIREBASE_STORAGE_EMULATOR_HOST is required')
  const [storageHostname, storagePort] = storageHost.split(':')
  connectStorageEmulator(storage, storageHostname, Number(storagePort))

  // Functions
  const functionsHost = import.meta.env.PUBLIC_FIREBASE_FUNCTIONS_EMULATOR_HOST
  if (!functionsHost) throw new Error('PUBLIC_FIREBASE_FUNCTIONS_EMULATOR_HOST is required')
  const [functionsHostname, functionsPort] = functionsHost.split(':')
  connectFunctionsEmulator(functions, functionsHostname, Number(functionsPort))
}

export { app, auth, firestore, storage, functions }

// ---------------------------------------------------------------------------
// Backend — Firebase Admin SDK connection
// data/firebase/firebase-emulator.ts
// ---------------------------------------------------------------------------
//
// import { initializeApp, applicationDefault } from 'firebase-admin/app'
// import { getFirestore } from 'firebase-admin/firestore'
// import { getDatabase } from 'firebase-admin/database'
// import { ENV } from '../../src/shared/config/env'
//
// export async function initializeFirebaseEmulator(projectId: string = 'my-project') {
//   const databaseURL = `http://${ENV.DATABASE_EMULATOR_HOST}/?ns=${projectId}-default-rtdb`
//
//   if (ENV.DATABASE_EMULATOR_HOST) {
//     process.env.FIREBASE_DATABASE_EMULATOR_HOST = ENV.DATABASE_EMULATOR_HOST
//     process.env.FIREBASE_DATABASE_URL = databaseURL
//   }
//
//   const app = initializeApp({
//     projectId,
//     credential: applicationDefault(),
//     databaseURL,
//   })
//
//   const firestore = getFirestore(app)
//   if (!ENV.FIRESTORE_EMULATOR_HOST) {
//     throw new Error('FIRESTORE_EMULATOR_HOST is not configured')
//   }
//   firestore.settings({ host: ENV.FIRESTORE_EMULATOR_HOST, ssl: false })
//
//   const database = getDatabase(app)
//
//   return { firestore, database, app }
// }
